CONFIG:
  BORDER_SIZE: 300
  BORDER_NARROWING_TIME: 600

MESSAGES:
  HELPMSG: '&7[&5&l!&7] Команды плагина ClanWars:%new%&5/clanwars start &7- начать игру%new%&5/clanwars stop &7- принудительно остановить игру%new%&5/clanwars forcepvpstart &7- принудительно запустить дезматч%new%&5/clanwars createteam [&d&5название_команды] [&d&5цвет] &7- создать команду%new%&5/clanwars jointeam [&d&5название_команды] &7- вступить в команду%new%&5/clanwars reload &7- перезапустить конфиги плагина'
  NO_PERMS: '&7[&5&l!&7] Такой команды нет или у вас нет прав для её использования.'
  RELOAD_SUCCESSFUL: '&7[&5&l!&7] Конфигурации плагина успешно перезагружены.'
  DEATH: '&7[&5&l!&7] Вас убили и вы были переведены в режим наблюдателя.'
  GAME_START: '&7[&5&l!&7] До начала игры осталось &6&l30&7 секунд.'
  GAME_START_5_SECONDS: '&7[&5&l!&7] До начала игры осталось &4&l5&7 секунд.'
  PVP_ON: '&7[&5&l!&7] PVP режим был включён!'
  STOPPED: '&7[&5&l!&7] Игра завершается.'
  TEAMCREATED: '&7[&5&l!&7] Команда создана.'
  JOINEDTEAM: '&7[&5&l!&7] Вы успешно зашли в команду.'
  LOWARGS: '&7[&5&l!&7] Вы вввели команду не полностью. Используйте /clanwars или /cw для помощи'
  GAME_NOT_STARTED: '&7[&5&l!&7] Вы не можете запустить дезматч если игра не началась!'
  TEAM_NOT_FOUND: '&7[&5&l!&7] Название команды введено не верно или команды не существует.'
  TEAM_ALREADY_EXISTS: '&7[&5&l!&7] Такая команда уже существует'
  DEATHMATCH_10_SEC: '&7[&5&l!&7] До начала дезматча осталось &c&l10&7 секунд.'